name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Authentification à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t mydockerhubusername/my-node-api:${GITHUB_SHA} .

      # Pousser l'image Docker sur Docker Hub
      - name: Push Docker image
        run: |
          docker push mydockerhubusername/my-node-api:${GITHUB_SHA}
